In [ ]:
import numpy as np

#Small Array

small_array=np.array([[3,6],[7,9]])

#Repeat across each dimensions

repeated_array = np.tile(small_array, (3, 2))

print("Repeated Array:")
print(repeated_array)

Repeated Array:
[[3 6 3 6]
 [7 9 7 9]
 [3 6 3 6]
 [7 9 7 9]
 [3 6 3 6]
 [7 9 7 9]]


In [ ]:
# Define the shape of the array
array_shape = (3, 7)

# Generate the array with element indexes in ascending order
ascending_array = np.arange(np.prod(array_shape)).reshape(array_shape)

print("Ascending Array:")
print(ascending_array)


Ascending Array:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
